KhronosGroup/Vulkan-Profiles

PROFILES.md, library/include/vulkan/debug/vulkan_profiles.hpp, library/include/vulkan/vulkan_profiles.hpp, library/scripts/genvp.py, library/source/debug/vulkan_profiles.cpp, library/source/vulkan_profiles.cpp
This PR fixes the following issues:
- Missing new line in the debug output when using the debug version of the library with the default (`stderr`) callback value
- Add workaround for missing `limittype` attribute for `VkQueueFamilyProperties::queueFlags`
=> Bug fix for debug output and queueFlags

vku/vk_layer_settings.cpp
In some cases, TrimPrefix was getting called twice and asserting the second time since the prefix was already trimmed. Change this to an early out to tolerate these cases.
=> Fix TrimPrefix early assert in vk_layer_settings.cpp (vku)

CMakeLists.txt
The Vulkan-Loader stabilized release branch has been renamed to
sdk-1.3.204 in preparation for the upcoming SDK release.
=> build: use Vulkan-Loader 1.3.204

layer/tests/tests.cpp, profiles/test/data/VP_LUNARG_test_api.json
Some extensions were duplicated, `VK_KHR_global_priority` was missing.
=> profiles layer: Fix extensions in test profile

layer/profiles.cpp, layer/profiles.h, layer/tests/profiles_test_helper.h, layer/tests/tests.cpp, layer/tests/tests_mechanism.cpp
Allows data to be shared between the layer and the layer tests without creating copies.  Happy to namespace things differently or reorganize things and folks see fit.
=> Add header file for layer source

layer/VkLayer_khronos_profiles.json.in
This caused a crash when selecting the portability layers configuration in Vulkan Configurator
=> layer: fix missing macos preset entry

layer/profiles.cpp
There is no difference between these functions here, because when they get called simulated extensions have not been loaded yet and the arrays used in these functions are the same. But checking if the actual device has the extensions supported is the correct behaviour.
=> profiles layer: Use correct HasExtension function

layer/TUTORIAL.md, layer/profiles.cpp, layer/tests/tests.cpp
The Profiles Layer requires the `VK_KHR_get_physical_device_properties2` extension, without it it's not functional.
=> profiles layer: Add GetPhysDev2 extensions of not present

layer/profiles.cpp
Use KHR version of the `vkGetPhysicalDeviceFormatProperties2` function if the core function is not supported
=> profiles layer: Use correct version of GetPhysicalDeviceFormatProperties2

layer/profiles.cpp, layer/tests/profiles_test_helper.cpp, layer/tests/tests_promoted.cpp, profiles/test/data/VP_LUNARG_test_api.json, profiles/test/data/VP_LUNARG_test_api_alternate.json, profiles/test/data/VP_LUNARG_test_promoted_api.json
Promoted struct should be checked against the vulkan API version instead of extension. 
Effective API version is determined as in validation layers. 
Removed TransferDeviceValues as it's no longer needed, since all checks are correct and proper warnings will be emitted.
#103 will have to be rebased and updated from this
=> profiles layer: Fix checking features and properties support

layer/profiles.cpp
The pNext chain in VkFormatProperties2KHR must only be filled if any `VkFormatProperties3` were loaded.
=> profiles layer: Fix filling format properties pNext chain

schema/profile_schema.json, scripts/genvp.py
Also allow invoking the generator script only for JSON validation
purposes (as a convenience feature during testing).
=> Fix JSON schema profile name matching

library/include/vulkan/debug/vulkan_profiles.hpp, library/include/vulkan/vulkan_profiles.hpp, library/source/debug/vulkan_profiles.cpp, library/source/vulkan_profiles.cpp, scripts/genvp.py
Ziga's PR on the layer-side handling of queue family matching made me realize that the previous queue family matching generated to the library is not accurate, as it did check each profile defined queue family's properties, but didn't require the profile defined queue family requirements to be fulfilled by separate queue families of the device.
In the meantime I also found some other bugs in the queue family comparison code, so those are fixed too.
=> Fix and improve queue family matching in library

layer/tests/tests.cpp
Specifying a full desktop path will break Android tests. It is no longer necessary to give a path for the json file path settings as CMake sets up the correct path.
=> Fix json file path settings in layer tests.cpp

library/test/CMakeLists.txt
The Profiles Library Debug build is supposed to announce why a profile is not supported
by a device, which is important for figuring out issues like:
VP_ANDROID_baseline_2021.json unsupported on ShieldTV
https://github.com/KhronosGroup/Vulkan-Profiles/issues/87
The problem was that genvp.py wasn't generating messages at every location where
a profile was determined to be unsupported.  These changes add messages (some
more helpful than others) for all cases where support is determined to be
lacking, to the generator and thus also to the generated code.
The extra debug messages confuse the MockDebugMessageCallback, which expects
an exact set of messages in an exact order.  Since the test doesn't mock the
running device, running the test on different devices will produce different
sets of …
=> library: add missing debug messages

.gitignore, CMakeLists.txt, external/generated-jsoncpp/json/json-forwards.h, external/generated-jsoncpp/json/json.h, external/generated-jsoncpp/jsoncpp.cpp, layer/CMakeLists.txt, layer/tests/CMakeLists.txt, library/CMakeLists.txt, profiles/test/CMakeLists.txt
The former attempt to flatten the SDK build (by flattening only the
Vulkan dependencies) works for the Windows SDK build, but is insufficient
for the Linux SDK build.
These are the Linux constraints:
-   Linux package builds require that clean source packages be available for
all binary packages, and cannot have source we do not own in the source
tree.
-   The Linux container build is hardened, and cannot access the network to
download after the initial source checkout.
-   The Linux container is restricted to Python 3.6, and cannot load
the Python 3.7.2 required to run genvp.py.
The json dependency isn't actually being used, so it has been removed.
The googletest dependency is only needed when building tests, so
it has been hidden behind a new PROFILES_BUILD_TESTS configuration
variable …
=> build: even flatter SDK build

layer/profiles.cpp
`VkPhysicalDeviceBufferAddressFeaturesEXT` which is typedef of `VkPhysicalDeviceBufferDeviceAddressFeaturesEXT` was missing, revealed by generated layer that is in progress.
=> profiles layer: Add missing BufferAddressFeaturesEXT

layer/TUTORIAL.md
On https://vulkan.lunarg.com/doc/sdk/1.3.204.1/windows/profiles_layer.html the profiles layers settings are added twice :
- Once manually 
- Once thanks to the automagic doc pipeline
THis PR remove the all manual settings documentation.
=> layer: update doc for automagic pipeline

CMakeLists.txt, layer-utils/vk_layer_settings.cpp, layer/CMakeLists.txt
Addressing issue:
Build of Vulkan-Profiles fails on Fedora 34
https://github.com/KhronosGroup/Vulkan-Profiles/issues/167
There are two issues here:
-   Building the Vulkan-Profiles layer requires the Python jsonschema module.
-   Fedora compilers give more warnings that Ubuntu compilers.
The build works if the Python "jsonschema" module is added to the
building system, and if -Werror is removed from layers/CMakeLists.txt.
To avoid requiring users to install "jsonschema", a new switch
REGENERATE_LAYER is provided.  If ON (the default), the layer code
for profiles.cpp is generated normally via the gen_layer.py script.
If OFF, the committed repository code for profiles.cpp is used directly
without first regenerating.  The "vulkansdk" script and the SDK
builds will explicitly turn this OFF. …
=> issue 167: add REGENERATE_LAYER and FATAL_WARNINGS switches

library/include/vulkan/debug/vulkan_profiles.hpp, library/include/vulkan/vulkan_profiles.hpp, library/source/debug/vulkan_profiles.cpp, library/source/vulkan_profiles.cpp, scripts/genvp.py
if you have set warnings as errors, it causes problems
=> script: fix unused variable warnings

scripts/genvp.py
`bits`, `minpot` and `minmul` are new limittypes we are introducing to improve the checking of some capabilities and creating a tool to combine profiles.
`bits` behaves like `max` for the toolset except that is used so that the Vulkan developers know they can use samller values while `bits` is the value effectively used by the driver and hardware. This said, contrary to other "behavior" capabilities, this one can be emulate to less bits.
`minpot` behaves like the `min` limittype but the value also need to be a power of two value. It's typically used for alignment values and will be particularly useful to create a tool to combine profiles.
`minmul` behaves like the `min` limittype but the value also need to be a multiple of the set value. It's typically used for `granularity` values. When …
=> Document types that should be `bits`, `minpot` and `minmul` limit types

OVERVIEW.md, README.md, layer-utils/CMakeLists.txt, layer/tests/CMakeLists.txt, layer/tests/profiles_test_helper.cpp, layer/tests/tests.cpp, layer/tests/tests_combine_intersection.cpp, layer/tests/tests_combine_union.cpp, layer/tests/tests_mechanism.cpp, layer/tests/tests_promoted.cpp, library/test/test_api_create_device.cpp, library/test/test_api_reflection.cpp, library/test/test_mocked_api_create_device.cpp, library/test/test_mocked_api_create_instance.cpp, library/test/test_mocked_api_get_instance_profile_support.cpp, library/test/test_mocked_api_get_physdev_profile_support.cpp, library/test/test_util.cpp, profiles/VP_ANDROID_baseline_2021.json, profiles/VP_ANDROID_baseline_2022.json, profiles/test/test_validate.cpp, scripts/gen_profiles_layer.py, scripts/gen_profiles_solution.py
Add Android Baseline 2022 v1 profile
Add Android Baseline 2021 v2 profile, removing shaderImageGatherExtended requirement
=> Android Baseline 2022 v1 and Android Baseline 2021 v2

CMakeLists.txt, layer-utils/CMakeLists.txt
This reflects how we ship the VulkanSDK and simplifies the CMake code.
=> cmake: Treat VVL includes as part of Vulkan::Headers

CMakeLists.txt
profiles doesn't have a 'cmake/' directory
=> cmake: Remove append to module path

CMakeLists.txt, layer/tests/CMakeLists.txt, layer/tests/profiles_test_helper.cpp, library/test/CMakeLists.txt
Instead of relying on the output of the binary directory it's best to use generator expressions to properly setup the environment.
$<TARGET_FILE_DIR:VkLayer_khronos_profiles> returns the directory where VkLayer_khronos_profiles ends up and works with debug/release builds.
=> cmake: Use generator expression instead of hardcoded paths

.github/workflows/profiles.yml, CMakeLists.txt, scripts/CMakeLists.txt, scripts/known_good.json
Optimizes vvl ci by not downloading loader if we don't need to (IE we are not building tests)
Move update deps CMake logic to scripts/CMakeLists.txt (This matches what the loader/vvl currently do)
=> known_good.json optimization & cleaning up update_deps.py

layer/VkLayer_khronos_profiles.json.in
Replace Baseline 2022 by Portability 2023 profile.
- The new Baseline 2023 profiles was not used by presets
- The Baseline 2022 was redondant with the Portability 2022 preset.
Portability extension is enabled thanks to the profiles layer settings.
=> profile: add portability 2023 preset

scripts/gen_profiles_layer.py
in `FillFormatPropertiesPNextChain` we are setting the new `VkFormatProperties3` but currently it is removing the `sType` from the original struct
=> profile: Fix VkFormatProperties3 setting wrong sType

profiles/CMakeLists.txt
closes #385
EX installation output:
```
juan@pop-os:~/projects/profiles$ cmake --install build/ --prefix build/install
-- Install configuration: "Debug"
-- Up-to-date: /home/juan/projects/profiles/build/install/Config/VK_LAYER_KHRONOS_profiles/VP_ANDROID_baseline_2021.json
-- Up-to-date: /home/juan/projects/profiles/build/install/Config/VK_LAYER_KHRONOS_profiles/VP_ANDROID_baseline_2022.json
-- Installing: /home/juan/projects/profiles/build/install/Config/VK_LAYER_KHRONOS_profiles/VP_KHR_roadmap_2022.json
-- Installing: /home/juan/projects/profiles/build/install/Config/VK_LAYER_KHRONOS_profiles/VP_LUNARG_desktop_baseline_2022.json
-- Installing: /home/juan/projects/profiles/build/install/Config/VK_LAYER_KHRONOS_profiles/VP_LUNARG_desktop_baseline_2023.json
-- Installing: …
```
=> cmake: Fix json installation

layer/tests/tests_combine_union.cpp, layer/tests/tests_mechanism.cpp, scripts/gen_profiles_layer.py
Improve performance using various techniques:
* Make `format` happen only if the message is to be logged
* Put extensions into unordered_maps to speed up queries
* Making a constructor public to allow emplace to work correctly
* Use C++17's unordered_map::extract to rename the key a value is associated with
* Pass by reference instead of value into functions
Since this is a whole lot of changes, it is suggested to look at each commit individually rather than all the changes all together. I tried to group them by what they do to make it easier to review & understand what each change is doing.
I validated these improvements by writing a very basic timer class that was added to each function/in multiple places in each function. I found that before the changes, the profile layer took ~40-50ms …
=> Improve Profiles Layer performance

layer/VkLayer_khronos_profiles.json.in, layer/profiles_settings.cpp, layer/profiles_settings.h, layer/profiles_util.cpp, layer/profiles_util.h, layer/tests/tests_mechanism.cpp, scripts/gen_profiles_layer.py
The original plan was to add "force physical device" to the loader but I suggested Charles to do it in the Profiles layer instead.
It's really a Vulkan developer tool and it releaves him from some work on the Vulkan Loader and it's probably a lot quicker and a less risky to do it in the Profiles layer (and with few changes in Vulkan Configurator).
By Device UUID:
By Device Name:
=> layer: add force physical device setting

profiles/VP_LUNARG_desktop_baseline_2023/vp_gpuinfo_amd_radeon_pro_vega_48_0_2_2009_osx_13_1.json, profiles/VP_LUNARG_desktop_baseline_2023/vp_gpuinfo_apple_m1_max_0_2_2011_osx_13_2.json, profiles/VP_LUNARG_desktop_baseline_2023/vp_gpuinfo_intel_r__uhd_graphics_630_0_2_2009_osx_13_2.json
It looks like MoltenVK change (and actually fixed) the report for `lineWidthGranularity` however the desktop 2023 profile is built with old reports so hack a workaround.
=> profile: fix desktop baseline 2023 lineWidthGranularity

scripts/gen_profiles_layer.py, scripts/gen_profiles_tests.py
seems the XML was fixed when `VK_EXT_rasterization_order_attachment_access` was created
Noticed a VVL test not running even though the features were enabled
=> scripts: Fix rasterization_order_attachment_access exception

.github/workflows/profiles.yml, CMakeLists.txt, layer/CMakeLists.txt, library/CMakeLists.txt, profiles/CMakeLists.txt, scripts/CMakeLists.txt
Because we routinely have to update `update_deps.py` it's much easier if this variable is consistent across repos using this script.
Also testing should be OFF by default.
This makes the library easier to package/build. This is already done in other vulkan repos we manage.
=> cmake: Use BUILD_TESTS

CHANGELOG.md, scripts/gen_profiles_layer.py
This issue was find when using a profile requiring `VK_EXT_mutable_descriptor_type`, when querying the required capabilities in `VkPhysicalDeviceMutableDescriptorTypeFeaturesEXT` the structure was empty because the layer would only check with the aliased extension `VK_VALVE_mutable_descriptor_type`,
=> layer: Fix query of capabilities of aliased extensions

scripts/gen_profiles_layer.py
The Profiles layer generates warnings if a profile _**disables**_ a feature that is otherwise _**supported**_ by the device with messages like this:
`'%s' profile value is enabled in the profile, but the device (%s) does not support it.`
That just doesn't make sense, as such warnings should only be generated if a profile would want to _**enable**_ a feature that is _**not supported**_ by the device.
This change fixes that.
=> layer: Fix invalid feature warning

scripts/gen_profiles_layer.py
The code that injects `VK_KHR_protability_subset` in `vkEnumerateDeviceExtensionProperties` is all wrong which results in incorrect value returned in `pCount`, as well as causing segfaults if the profile does not include any extensions.
This change fixes that.
=> layer: Fix EnumerateDeviceExtensionProperties segfault

layer/vk_layer_table.cpp, layer/vk_layer_table.h
The Profiles layer leaks memory on exit because the dispatch tables allocated never get destroyed.
This is observable by running some tests with AddressSanitizer.
The source has `destroy_device_dispatch_table` and `destroy_instance_dispatch_table` functions that are supposed to delete these allocations, but they are never called from anywhere.
Instead, this fix simply uses `unique_ptr`s to make sure that these allocations always get released when the layer is unloaded.
=> layer: Fix dispatch table memory leak

scripts/gen_profiles_layer.py, scripts/gen_profiles_solution.py
This PR introduces some improvements to the generator scripts to better handle API variants defined in the vk.xml, as the previous code did not handle some of the aspects of the new vk.xml syntaxes introduced for API variant dependent definitions in a general way.
=> scripts: Improve handling of API variants

BUILD.md
Fix inaccurate/confusing text
Remove dependencies section. Very prone to being outdated.
Remove section implying we test Ubuntu 18.04 LTS. We don't.
=> docs: Update BUILD.md

scripts/gen_profiles_layer.py
The profiles layer still referred to an old provision structure name that no longer exists.
=> layer: Fix video queue family structure name

layer/CMakeLists.txt
Similar to https://github.com/KhronosGroup/Vulkan-Tools/pull/881 
Need a way to enable `VK_USE_PLATFORM_ANDROID_KHR` when running on desktop in order to test Android Hardware Buffers without a physical device
=> cmake: Add MockAHB support

scripts/gen_profiles_layer.py
There are a few more KHR GPDP2 dependencies left in the generator script beyond what I've fixed in https://github.com/KhronosGroup/Vulkan-Profiles/pull/479.
=> layer: Fix more KHR GPDP2 dependencies

layer/tests/profiles_test_helper.cpp
14 unit tests were failing on macOS because the instance creation code did not enable the portability enumeration flag.
Now, these tests are still failing, but for other reasons (some crash). Many look like they are assuming some features are available on macOS which aren't. I can try and sort through these, but the profiles code is complex. If @christophe-lunarg could please take a look on his mac by running the tests after this fix is merged, and perhaps some of them are 'easy' to fix with his pre-existing knowledge of the profiles test code ;-)
=> tests: Added portability enumeration flag to instance creation

layer/profiles_settings.cpp
Fixes Android logs to print the input values given, rather than printing the formatting specifiers (e.g. '%s') in the message.
=> Fix logging on Android to correctly print formatted input values

profiles/VP_ANDROID_15_minimums.json
Because the published VPA15 is for software developers (to use to filter devices to use Vulkan with) and not simply for hardware developers.
=> Update VPA15 description

scripts/gen_profiles_solution.py
This change cause failure on the Validation layer and with more investigations, it seems wrong.
=> Fix regression on `SubgroupSize` limittype

profiles/CMakeLists.txt
This was discovered during SDK integration builds.
Commit 3e32c809696dcbe81c31c1d04fc2ca62d1f584aa broke installation of the gen_profiles_file.py script, because it renamed MERGE_PYTHON_FILES and LAYER_PYTHON_FILES to MERGE_SCRIPT and SOLUTION_SCRIPT, respectively, in CMakeLists.txt:
-set(MERGE_PYTHON_FILES ${PROJECT_SOURCE_DIR}/scripts/gen_profiles_file.py)
-set(LAYER_PYTHON_FILES ${PROJECT_SOURCE_DIR}/scripts/gen_profiles_solution.py)
+set(MERGE_SCRIPT ${PROJECT_SOURCE_DIR}/scripts/gen_profiles_file.py)
+set(SOLUTION_SCRIPT ${PROJECT_SOURCE_DIR}/scripts/gen_profiles_solution.py)
but neglected to change the MERGE_PYTHON_FILES reference in profiles/CMakeLists.txt, where the install target is defined (note that SOLUTION_SCRIPT was correctly changed):
install(
FILES
${MERGE_PYTHON_FILES}
- …
=> sdk: fix install of gen_profiles_file.py

scripts/gen_profiles_layer.py
Ignore host image copy structs when filling pNext chains of query functions
=> profiles: Ignore host image copy structs in pNext chains

scripts/gen_profiles_layer.py
follow-up for https://github.com/KhronosGroup/Vulkan-Profiles/pull/663
the issue with ignoring `VkPhysicalDeviceHostImageCopyFeaturesEXT` is no one using the profiles layer can expose support for it
The main use case here is we (VVL) have the feature and properties passed back up, but now the `hostImageCopy` gets saved but since there is not switch case it is not set
=> profiles: Don't ignore VkPhysicalDeviceHostImageCopyFeaturesEXT

profiles/VP_ANDROID_baseline_2021.json, profiles/VP_ANDROID_baseline_2022.json
It was discovered that `minMemoryMapAlignment` should not have been in these profiles, and so they are being removed from both Android Baseline Profiles.
=> Remove minMemoryMapAlignment from ABP 2021 and 2022

scripts/gen_profiles_layer.py
Fix checking which extension the device supports. Currently only the original extension was checked and not any of the promoted to extensions. This was an issue with a corner case when a device would support a promoted extension but not the original one.
For example a device could support `VK_EXT_mutable_descriptor_type`, but not `VK_VALVE_mutable_descriptor_type`.
=> layer: Fix checking device supported extensions

layer/tests/CMakeLists.txt, layer/tests/platforms/android/AndroidManifest.xml, library/test/CMakeLists.txt, library/test/platforms/android/AndroidManifest.xml
There's an issue with Android 14 that will cause a prompt to display on the phone  when trying to run tests. This can cause an issue with CI as the prompt needs to be hit before the tests begin to run. The prompt displays:
```
This app was built for an older version of Android. It might not work
properly and doesn't include the latest security and privacy
protections.  Check for an update, or contact the app's developer
```
Also, apksigner will be used instead of jarsigner. apksigner has since replaced jarsigner. Builing for for newer version of android will produce  this error when trying to use jarsigner:
```
ERROR: unexpected exception:
_run(/home/lunarg/Android/Sdk/platform-tools/adb -s R5CX21HV9TJ
install -r -g -t
/home/lunarg/.jenkins/workspace/manual-VulkanProfiles/VulkanProfiles/an …
```
=> tests: Update android targetSdkVersion from 26 to 33

.github/workflows/ci.yml, profiles/CMakeLists.txt, profiles/VP_ANDROID_16_minimums.json, profiles/test/test_validate.cpp
This is the "Vulkan Profile for Android 16" (a.k.a. VPA16). It will be required for chipsets starting or restarting Google Requirements Freeze with Android 16. It depends on VPA15, which in turn depends on ABP 2022.
=> Add Android 16 profile

profiles/VP_ANDROID_16_minimums.json
Our last change to VP_ANDROID_16_minimums.json attempted to allow Mali G52/G72 Bifrost be supported, by delaying some requirements to the upcoming VP_ANDROID_16_minimums.json.  Since then, we received some corrections from Arm.  This change should be correct now.
=> Delay some requirements that Mali Bifrost chipsets cannot do

OVERVIEW.md, layer/CMakeLists.txt, layer/VkLayer_khronos_profiles.json.in, layer/profiles_settings.h, layer/profiles_util.h, layer/tests/CMakeLists.txt, layer/tests/tests_combine_intersection.cpp, layer/tests/tests_combine_union.cpp, layer/tests/tests_mechanism_video_profiles.cpp, layer/tests/tests_util.cpp, library/TUTORIAL.md, library/test/mock_vulkan_api.hpp, library/test/profiles/VP_LUNARG_test_variants.json, library/test/profiles/VP_RASTERGRID_test_queue_families.json, library/test/profiles/VP_RASTERGRID_test_video_profiles.json, library/test/profiles/VP_RASTERGRID_test_wildcard_video_profiles.json, library/test/test_mocked_api_create_device.cpp, library/test/test_mocked_api_create_instance.cpp, library/test/test_mocked_api_generated_library.cpp, profiles/test/data/VP_RASTERGRID_test_video_profiles.json, scripts/CMakeLists.txt, scripts/gen_profiles_file.py, scripts/gen_profiles_layer.py, scripts/gen_profiles_solution.py, scripts/gen_profiles_tests.py
This PR adds support for defining video profiles and corresponding video capabilities and video format properties in the profile JSONs.
The change adds this support to the following components (through codegen):
- Vulkan Profiles schema
- Vulkan Profiles documentation
- Vulkan Profiles Library
- Vulkan Profiles Layer
In addition, this also adds back support for queue family properties in the Vulkan Profiles Library which was removed at some point.
=> profiles: Add video profiles support

scripts/gen_profiles_layer.py
`vkGetPhysicalDeviceImageFormatProperties2KHR()` accidentally ignored `pNext->VkPhysicalDeviceImageDrmFormatModifierInfoEXT` as it calls `GetPhysicalDeviceImageFormatProperties()` instead of the `2` variant of the function. This is against [VUID-vkGetPhysicalDeviceImageFormatProperties-tiling-02248](https://registry.khronos.org/vulkan/specs/latest/man/html/vkGetPhysicalDeviceImageFormatProperties.html#VUID-vkGetPhysicalDeviceImageFormatProperties-tiling-02248) so fix that by calling `vkGetPhysicalDeviceImageFormatProperties2()`.
Previously the result of `dt->GetPhysicalDeviceImageFormatProperties2` was also being ignored and I think the intention was to do this anyway looking at the code.
Came across this when I was using the profile layer with a game which would segfault in Turnip since …
=> profiles: Fix DRM format handling

scripts/gen_profiles_layer.py
@ziga-lunarg tried to use https://github.com/KhronosGroup/Vulkan-Profiles/pull/746 in VVL and found you missed the `VkPhysicalDeviceVulkan14Properties` in this one spot that would cause things to crash
=> Add missing VkPhysicalDeviceVulkan14Properties array size

layer/VkLayer_khronos_profiles.json.in, layer/profiles.h, layer/profiles_settings.cpp, layer/profiles_settings.h, scripts/gen_profiles_layer.py
The new option allows to first load all the features from a driver, so if the vulkan profiles does not know about a features struct and will not write to it, then it will have the device values
Closes #775
=> profiles: Add option to load unknown features from driver

scripts/gen_profiles_solution.py
Initialize these variables to empty so later checks don't fail. Fixes:
AttributeError: 'VulkanRegistry' object has no attribute 'videoCodecsByValue'
This issue replaced https://github.com/KhronosGroup/Vulkan-Profiles/pull/791
=> profiles: Fix gen_profiles_solution w/o video xml

scripts/known_good.json
Modules are defaulted to off, so setting it manually isn't necessary.
=> scripts: Remove useless VulkanHeaders cmake option
