KhronosGroup/Vulkan-Profiles

layer/profiles.cpp
Fix checking if env variable is not set.
=> profiles layer: Fix getting SDK env variable

layer/profiles.cpp
Mostly minor stuff -- some tweaking of the json loader/parser arg and fixed some API names.
=> Various layer issues encountered during Android port

layer/TUTORIAL.md
=> profiles layer: Update tutorial

layer/TUTORIAL.md
=> profiles layer tutorial: Warn about using multiple versions of same structure

OVERVIEW.md
Couldn't get git to recognize the correct Unicode copyright symbol, so just changing it to (c)
=> doc: update copyright symbol to (c) on overview.md

layer/profiles.cpp
When `fail_on_error` setting is used all warnings should be printed before failing.
=> profiles layer: Print all warnings before failing

layer/profiles.cpp
Avoids a bit of confusion.  At least, it was confusing to me.
=> Change extension/format setting types to vku::Strings

layer/profiles.cpp
The checks for adding promoted structures were not correct and validation layers gave warnings. 
Promoted structs must only be used when the instance is created with the required version or above.
=> profiles layer: Fix checking vk version

layer/VkLayer_khronos_profiles.json.in, layer/profiles.cpp, layer/profiles.h
`${VP_DEFAULT}` is not a valid value and default value for the profile layer so select the first profile of a profiles file.
=> layer: implement  default value for profile_name setting

layer/profiles.cpp
JSON value => Profile value 
and
existing value => Device value
=> profiles layer: Improve message logs for profile and device values

layer/profiles.cpp
Replace `JSON file` with `Profile` in log messages.
=> profiles layer: Improve log messages

schema/profile_schema.json, scripts/genvp.py
=> Auto-generate schema version from header version

layer/tests/tests.cpp
Fixes test failure on Android.
=> Set fail-on-error for partial-qfp profiles layer test

library/test/test_api_create_device_android.cpp
One of the tests was not suitable for such old devices.  Added device detection and skipped if a ShieldTV device was recognized. Also removed some unused ifdefs, this test is only built on Android.
Bob confirmed this resulted in clean CI runs.
=> Skip failing Profiles Library Android test on ShieldTV devices

layer/profiles.cpp, layer/tests/tests.cpp
=> profiles layer: Set instance version from profile

schema/profile_schema.json, scripts/genvp.py
This makes sure only enums from core and vulkan extensions are found
=> generator script: Update finding enums

library/TUTORIAL.md
Only noticeable if you literally do the tutorial :cowboy_hat_face:
=> tutorial: fix examples

layer/profiles.cpp
Not sure when these values changed, but the rerunning the script updates them.
=> profiles: Update generated profile

layer/profiles.cpp, layer/tests/tests_generated.cpp, profiles/VP_LUNARG_desktop_baseline_2022.json, profiles/VP_LUNARG_desktop_portability_2022.json, profiles/VP_LUNARG_desktop_portability_2022/VP_LUNARG_desktop_baseline_2022.json, profiles/test/data/VP_LUNARG_test_api_generated.json, profiles/test/data/VP_LUNARG_test_combine_intersect.json, profiles/test/data/VP_LUNARG_test_combine_union.json, profiles/test/data/VP_LUNARG_test_generated_name.json, schema/profiles-0.8-latest.json, scripts/gen_profiles_layer.py, scripts/known_good.cmake
- Update to header 226
- Add workaround for mesh shader nv variable names
=> profiles: Update to 226 header

CMakeLists.txt, external/generated-jsoncpp/json/json-forwards.h, external/generated-jsoncpp/json/json.h, external/generated-jsoncpp/jsoncpp.cpp
I just hit #167 trying to build this repo for the first time on Arch. I did a little digging and it has actually been fixed upstream for a while.
Fixes #167
=> build: Update jsoncpp to 1.9.5

scripts/gen_profiles_solution.py
=> schema: allow factorizing history and contributors

layer-utils/CMakeLists.txt, layer-utils/vk_layer_settings.cpp, layer-utils/vk_layer_settings.h
=> vku cleanup

.github/workflows/profiles.yml, CMakeLists.txt, layer/CMakeLists.txt, layer/VkLayer_khronos_profiles.def, layer/VkLayer_khronos_profiles.json.in, layer/VkLayer_khronos_profiles.map, scripts/gen_profiles_layer.py
Now the profiles binary and it's corresponding json will be installed to the correct location.
Partially address https://github.com/KhronosGroup/Vulkan-Profiles/issues/372
=> Install library and corresponding json

.github/workflows/profiles.yml, BUILD.md, CMakeLists.txt
- Raise minimum to 3.17.2
- Explicilty test 3.17.2 via github actions similar to the vulkan validation layers
=> Update CMake minimum to 3.17

CHANGELOG.md, layer/VkLayer_khronos_profiles.json.in, layer/profiles.h, layer/tests/tests_mechanism.cpp, scripts/gen_profiles_layer.py
=> layer: add setting to control vulkan feature init

CHANGELOG.md, CMakeLists.txt, layer/profiles.h, layer/tests/tests_mechanism.cpp, profiles/test/data/VP_LUNARG_test_variants.json, scripts/gen_profiles_layer.py
When a Profile defines multiple Profile variants, all variants are emulated by the profiles layer.
=> layer: add support of multiple variants

.github/workflows/profiles.yml, scripts/CMakeLists.txt, scripts/known_good.json, scripts/update_deps.py
Copying lots of build improvements over from VVL
EX. Now its possible to use Ninja on Windows with the fixes to update_deps.py
Also the performance enhancements to scripts/CMakeLists.txt
=> Build fixes/enhancements

layer/CMakeLists.txt, layer/profiles.h, layer/profiles_settings.cpp, layer/profiles_settings.h, layer/profiles_util.cpp, layer/profiles_util.h, layer/tests/CMakeLists.txt, scripts/gen_profiles_layer.py, scripts/known_good.json
This reverts commit aab9357ed58c68a3175a562ffa7b7456876d027a.
=> Revert "layer: use layer settings librarie"

CHANGELOG.md, layer/profiles_util.cpp, layer/profiles_util.h, scripts/gen_profiles_layer.py
This make using the profiles layer with multiple drivers system much more convenient / less confusing
=> layer: improve log messages with device name

profiles/VP_LUNARG_desktop_baseline_2022/vp_gpuinfo_amd_radeon__tm__r7_370_series_2_0_179_windows_10.json, profiles/VP_LUNARG_desktop_baseline_2023/vp_gpuinfo_amd_radeon_pro_vega_48_0_2_2009_osx_13_1.json, profiles/VP_LUNARG_desktop_baseline_2023/vp_gpuinfo_apple_m1_max_0_2_2011_osx_13_2.json, profiles/VP_LUNARG_desktop_baseline_2023/vp_gpuinfo_intel_r__uhd_graphics_630_0_2_2009_osx_13_2.json, profiles/VP_LUNARG_desktop_baseline_2023/vp_gpuinfo_nvidia_geforce_gtx_680mx_0_0_159_24_osx_10_15.json, scripts/gen_profiles_file.py
macOS profiles incorrectly reported 0 for linewidth
=> profile: fix desktop 2023 linewidth

layer/tests/CMakeLists.txt, layer/tests/profiles_test_helper.h, layer/tests/tests_mechanism.cpp, layer/tests/tests_mechanism_api_version.cpp, layer/tests/tests_mechanism_check_values.cpp, layer/tests/tests_mechanism_format.cpp, layer/tests/tests_mechanism_physical_device_selection.cpp
To make it to debug only the formats for example
=> layer: split unit tests

scripts/gen_profiles_layer.py, scripts/gen_profiles_tests.py, scripts/known_good.json
There is one issue, the generator will complain that the struct `VkPhysicalDeviceHostImageCopyPropertiesEXT` is ill-formed, because it contains dynamic arrays
=> profiles: Update to header 260

scripts/gen_profiles_layer.py
The Profiles layer incorrectly depends on the KHR variant of GPDP2 in some places even when Vulkan 1.1 is available.
=> layer: Fix KHR GPDP2 dependency

.github/workflows/ci.yml
Set CMAKE_GENERATOR consistently
Set ccache consistently
Rename script/name to ci for simplicity
=> ci: Cleanup CI script

scripts/gen_profiles_layer.py
This PR enables proper handling of platform protection #defines in the Profiles Layer so that in case any extension specific to a platform introduces new device features or properties, then the layer will continue to build fine per the enabled `VK_USE_PLATFORM_XX` definitions.
At the moment there are no such Vulkan extensions, but that may change in the future.
No similar changes seem to be necessary for the Profiles Library, as the library is generated with specific profiles, and their definitions are only included if all the corresponding `VK_FOO_bar` definitions corresponding to the contained extensions are defined, which are already preconditioned by the corresponding platform protection #defines.
=> layer: Handle platform protect defines

scripts/gen_profiles_file.py
=> profiles: Fix removing element from dict

scripts/gen_profiles_file.py, scripts/gen_profiles_solution.py
Ideally, vk.xml should be fixed too and 'not' limitype added.
=> merge: Add workaround for 'not' limitype #435

scripts/gen_profiles_file.py
Adds dictionary search before checking for support on format properties and deletes any not-supported features for the intersection operation. 
A crash can be reproduced by using one json with VkFormatProperties3 and one without, on `gen_profiles_file.py --mode intersection` operation.  deviceA.json:
```
...
"formats": {
"VK_FORMAT_R4G4_UNORM_PACK8": {
"VkFormatProperties": {
"linearTilingFeatures": [
"VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT",
"VK_FORMAT_FEATURE_BLIT_SRC_BIT",
"VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT",
"VK_FORMAT_FEATURE_TRANSFER_SRC_BIT",
"VK_FORMAT_FEATURE_TRANSFER_DST_BIT",
"VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT",
"VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT"
],
"optimalTilingFeatures": [
"VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT", …
```
=> Handle intersection of profiles with different format features

layer/profiles_interface.cpp, scripts/gen_profiles_solution.py, scripts/known_good.json
- Add missing include in profiles_interface.cpp
- Add limittypes for `VkPhysicalDeviceRenderPassStripedPropertiesARM`
- Update header version
=> profiles: Update to header 272

library/test/test_api_create_device.cpp
=> test: Add extra tests for Roadmap 2024 and 2022

scripts/gen_profiles_solution.py
This change fixes dependency handling when a structure alias is part of the target API but the actual structure it aliases is not.
=> script: Fix structure alias dependency handling

layer/CMakeLists.txt
Builds the profiles layer as an iOS framework and meets Apple Appstore requirements.
=> ios: Build layer as valid appstore framework

profiles/VP_ANDROID_16_minimums.json
Removed features and extensions that Mali G52 are not able to meet.
=> Update VP_ANDROID_16_minimums.json to remove incompatible features and extensions

profiles/VP_ANDROID_16_minimums.json
Delay VK_EXT_device_fault until VPA17
=> Delay VK_EXT_device_fault until VPA17

layer/tests/tests_combine_intersection.cpp, layer/tests/tests_combine_union.cpp, profiles/test/data/VP_LUNARG_test_combine_intersect/VP_LUNARG_test_combine_intersect1.json, profiles/test/data/VP_LUNARG_test_combine_intersect/VP_LUNARG_test_combine_intersect2.json, profiles/test/data/VP_LUNARG_test_combine_union/VP_LUNARG_test_combine_union1.json, profiles/test/data/VP_LUNARG_test_combine_union/VP_LUNARG_test_combine_union2.json, scripts/gen_profiles_solution.py
=> profiles: Update overwriting xml limittypes

scripts/known_good.json
=> jsoncpp: Update to 1.9.6

profiles/test/data/VP_LUNARG_test_host_image_copy/local_gpu.json, profiles/test/data/VP_LUNARG_test_host_image_copy/remote_gpu.json, scripts/gen_profiles_file.py, scripts/gen_profiles_layer.py, scripts/gen_profiles_solution.py, scripts/gen_profiles_tests.py
Taking the layer part from #705
=> profiles: Add layer support for VK_EXT_host_image_copy

layer/tests/layer_tests_main.cpp
=> profiles: Update disabling dialog boxes on windows
